import { dawImportAudioUrl, type DawClip, type DawProject, type DawTrack } from './dawImportClient';
import { computePeaks, useEditorStore } from '../state/editorStore';
import { useAppUiStore } from '../state/appUiStore';
import { useStatusBarStore } from '../state/statusBarStore';
import { logError, logInfo } from '../state/logStore';
import { renderNotesToBlob, type RenderNote } from './midiSynth';
import type { PianoNote } from '../state/pianoRollStore';

const DEFAULT_CLIP_SECONDS = 4;

const dbToLinear = (db: number): number => {
  if (!Number.isFinite(db)) return 0.8;
  return Math.max(0, Math.min(1, 10 ** (db / 20)));
};

const clipDuration = (clip: DawClip): number =>
  Math.max(0.05, (clip.end_time ?? 0) - (clip.start_time ?? 0));

const isArrangementClip = (clip: DawClip): boolean =>
  clip.scene_index == null && clip.slot_index == null && (clip.start_time > 0 || clip.end_time > 0);

const sceneStartSec = (clip: DawClip, project: DawProject): number => {
  const sceneIndex = clip.scene_index ?? clip.slot_index ?? 0;
  const beatSec = 60 / Math.max(40, project.tempo || 120);
  return sceneIndex * 4 * beatSec;
};

const notesFromDawClip = (clip: DawClip): RenderNote[] => {
  if (!Array.isArray(clip.midi_notes)) return [];
  return clip.midi_notes.flatMap((raw) => {
    if (!raw || typeof raw !== 'object') return [];
    const note = raw as Record<string, unknown>;
    const midi = Number(note.midi ?? note.note ?? note.pitch);
    const startSec = Number(note.startSec ?? note.start_sec ?? note.start ?? 0);
    const durationSec = Number(note.durationSec ?? note.duration_sec ?? note.duration ?? 0.25);
    const velocityRaw = Number(note.velocity ?? 0.8);
    if (!Number.isFinite(midi) || !Number.isFinite(startSec) || !Number.isFinite(durationSec)) return [];
    return [{
      midi,
      startSec: Math.max(0, startSec),
      durationSec: Math.max(0.02, durationSec),
      velocity: velocityRaw <= 1 ? Math.round(velocityRaw * 127) : Math.round(velocityRaw),
    }];
  });
};

const pianoNotesFromRenderNotes = (notes: RenderNote[], bpm: number): PianoNote[] => {
  const stepSec = 60 / Math.max(40, bpm || 120) / 4;
  return notes.map((note, index) => ({
    id: `als-note-${index}-${Math.round(note.startSec * 1000)}`,
    note: note.midi,
    step: Math.max(0, Math.round(note.startSec / stepSec)),
    length: Math.max(1, Math.round(note.durationSec / stepSec)),
    velocity: Math.max(0, Math.min(1, note.velocity / 127)),
  }));
};

const loadClipAudio = async (clip: DawClip, project: DawProject): Promise<{
  blob: Blob;
  mimeType: string;
  duration: number;
  sourceKind?: 'audio' | 'piano-roll';
  sourcePianoRoll?: PianoNote[];
  sourceTotalSteps?: number;
}> => {
  if (clip.file_path) {
    const response = await fetch(dawImportAudioUrl(clip.file_path));
    if (!response.ok) throw new Error(`Could not load ${clip.name}`);
    const blob = await response.blob();
    const { duration } = await computePeaks(blob, 16);
    return { blob, mimeType: blob.type || 'audio/wav', duration };
  }

  const notes = notesFromDawClip(clip);
  if (notes.length === 0) throw new Error(`Clip has no audio or MIDI notes: ${clip.name}`);
  const rendered = await renderNotesToBlob(notes, { tailSec: 0.2 });
  const pianoNotes = pianoNotesFromRenderNotes(notes, project.tempo);
  return {
    blob: rendered.blob,
    mimeType: 'audio/wav',
    duration: rendered.duration,
    sourceKind: 'piano-roll',
    sourcePianoRoll: pianoNotes,
    sourceTotalSteps: Math.max(16, ...pianoNotes.map((note) => note.step + note.length)),
  };
};

export async function importDawProjectToEditor(project: DawProject): Promise<number> {
  const editor = useEditorStore.getState();
  editor.setBpm(project.tempo);

  const playableTracks = project.tracks.filter((track) => track.type === 'audio' || track.type === 'midi');
  const hasArrangement = playableTracks.some((track) => track.clips.some(isArrangementClip));
  let imported = 0;

  for (const [trackIndex, dawTrack] of playableTracks.entries()) {
    const dawClips = hasArrangement
      ? dawTrack.clips.filter(isArrangementClip)
      : dawTrack.clips.filter((clip) => clip.file_path || notesFromDawClip(clip).length > 0);
    if (dawClips.length === 0) continue;

    const trackId = editor.addTrack({
      name: dawTrack.name || `Track ${trackIndex + 1}`,
      nameAutoGenerated: false,
      volume: dbToLinear(dawTrack.volume_db),
      pan: Math.max(-1, Math.min(1, dawTrack.pan || 0)),
      mute: dawTrack.mute,
      solo: dawTrack.solo,
    });
    const trackColor = useEditorStore.getState().tracks.find((track) => track.id === trackId)?.color ?? '#8b5cf6';

    for (const clip of dawClips) {
      try {
        const loaded = await loadClipAudio(clip, project);
        const { peaks, duration } = await computePeaks(loaded.blob, 240);
        const sourceDuration = loaded.duration || duration || clipDuration(clip);
        const startSec = hasArrangement ? Math.max(0, clip.start_time || 0) : sceneStartSec(clip, project);
        const durationSec = hasArrangement
          ? Math.min(sourceDuration, clipDuration(clip) || sourceDuration)
          : sourceDuration || DEFAULT_CLIP_SECONDS;
        const clipId = useEditorStore.getState().addClipToTrack({
          trackId,
          label: clip.name || dawTrack.name || 'Imported clip',
          audioBlob: loaded.blob,
          mimeType: loaded.mimeType,
          sourceDuration,
          offsetIntoSource: 0,
          durationSec,
          startSec,
          color: trackColor,
          sourceKind: loaded.sourceKind,
          sourcePianoRoll: loaded.sourcePianoRoll,
          sourceBpm: loaded.sourceKind === 'piano-roll' ? project.tempo : undefined,
          sourceTotalSteps: loaded.sourceTotalSteps,
        });
        useEditorStore.getState().cachePeaks(clipId, peaks);
        imported += 1;
      } catch (error) {
        logError('dawimport', error instanceof Error ? error.message : String(error));
      }
    }
  }

  if (project.locators.length > 0) {
    const store = useEditorStore.getState();
    project.locators.forEach((locator) => store.addMarker(locator.position, locator.name));
  }

  useAppUiStore.getState().setCenterTab('edit');
  useStatusBarStore.getState().setText(
    imported > 0 ? `IMPORTED ${imported} CLIP(S) TO EDIT TIMELINE` : 'NO PLAYABLE CLIPS FOUND FOR TIMELINE',
  );
  logInfo('dawimport', `Imported ${imported} clip(s) from ${project.name} to the editor timeline`);
  return imported;
}

